Repository Vactor0911/mokwon-guide, pull requests merged in 2025-05, with the labels that each got.

#19 건물 상세 정보 드로어 메뉴 구현
  package-lock.json
  public/images/building_images/n_1.jpg
  src/components/BuildingDetailDrawer.tsx
  src/components/Header.tsx
  src/pages/Main.tsx
  src/theme/index.ts
Labels: 개선

#23 useMediaQuery 후크 리팩토링
  src/components/MapViewer.tsx
Labels: 개선

#24 Hits
  .gitignore
  src/components/Header.tsx
  src/components/SearchDrawer.tsx
  src/states/index.ts
  src/utils/index.ts
Labels: 개선

#25 Hits
  .gitignore
  package-lock.json
  package.json
  src/components/SearchDrawer.tsx
  src/components/SearchHistory.tsx
  src/components/SearchResults.tsx
  src/utils/index.ts
Labels: 개선

#26 Hits
  src/assets/buildings.json
  src/components/SearchDrawer.tsx
  src/components/SearchHistory.tsx
  src/components/SearchResultItem.tsx
  src/components/SearchResults.tsx
  src/utils/index.ts
Labels: 개선

#27 라이브러리 디펜던시 수정
  package-lock.json
  package.json
  src/utils/index.ts
Labels: 오류 의심

#28 검색 결과 및 검색 기록 구현
  src/assets/buildings.json
  src/assets/facilities.json
  src/components/DrawerMenu.tsx
  src/components/Header.tsx
  src/components/HighlightedText.tsx
  src/components/MapViewer.tsx
  src/components/SearchDrawer.tsx
  src/components/SearchHistory.tsx
  src/components/SearchResultButton.tsx
  src/components/SearchResultItem.tsx
  src/components/SearchResults.tsx
  src/states/index.ts
  src/utils/index.ts
  src/utils/search.ts
  src/utils/security.ts
Labels: 개선

#29 컴포넌트 스타일 수정
  src/components/DrawerMenu.tsx
  src/components/MapViewer.tsx
Labels: 개선

#30 검색바 구현
  .gitignore
  package-lock.json
  package.json
  src/assets/buildings.json
  src/assets/facilities.json
  src/components/DrawerMenu.tsx
  src/components/Header.tsx
  src/components/HighlightedText.tsx
  src/components/MapViewer.tsx
  src/components/SearchDrawer.tsx
  src/components/SearchResultButton.tsx
  src/states/index.ts
  src/utils/index.ts
  src/utils/search.ts
  src/utils/security.ts
Labels: 개선

#33 지도 뷰어 마커 및 상세 페이지 기능 구현
  public/images/building_images/a.jpg
  public/images/building_images/b.jpg
  public/images/building_images/c.jpg
  public/images/building_images/d.jpg
  public/images/building_images/e.jpg
  public/images/building_images/f.jpg
  public/images/building_images/g.jpg
  public/images/building_images/g1.jpg
  public/images/building_images/i.jpg
  public/images/building_images/j.jpg
  public/images/building_images/k.jpg
  public/images/building_images/m.jpg
  public/images/building_images/n.jpg
  public/images/building_images/o.jpg
  public/images/building_images/o1.jpg
  public/images/building_images/p.jpg
  public/images/building_images/r.jpg
  public/images/building_images/t.jpg
  public/images/building_images/u.jpg
  public/images/building_images/v.jpg
  public/images/building_images/w.jpg
  src/assets/buildings.json
  src/assets/facilities.json
  src/components/BuildingDetailDrawer.tsx
  src/components/BuildingLayoutViewer.tsx
  src/components/BuildingMarker.tsx
  src/components/Header.tsx
  src/components/MapViewer.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/states/index.ts
  src/utils/index.ts
  src/utils/search.ts
Labels: 개선

#36 마커 컴포넌트 분리 및 내 위치 마커 구현
  src/components/BuildingDetailDrawer.tsx
  src/components/BuildingLayoutViewer.tsx
  src/components/BuildingMarker.tsx
  src/components/CircularMarker.tsx
  src/components/MapViewer.tsx
  src/components/SearchResultButton.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/utils/index.ts
Labels: 개선

#37 프로젝트 디버깅 및 리팩토링
  src/assets/icons/GitHub.png
  src/assets/icons/Github.svg
  src/assets/icons/GoogleForms.svg
  src/components/BuildingDetailDrawer.tsx
  src/components/BuildingLayoutViewer.tsx
  src/components/Footer.tsx
  src/components/SearchResultButton.tsx
  src/pages/Detail.tsx
  src/utils/index.ts
  src/utils/search.ts
Labels: 개선

#39 프로젝트 리팩토링, 디버깅 및 배포 준비
  .github/workflows/deploy.yml
  package.json
  public/404.html
  src/App.tsx
  src/assets/facilities.json
  src/assets/icons/GitHub.png
  src/assets/icons/Github.svg
  src/assets/icons/GoogleForms.svg
  src/components/BuildingDetailDrawer.tsx
  src/components/BuildingLayoutViewer.tsx
  src/components/BuildingMarker.tsx
  src/components/CircularMarker.tsx
  src/components/Footer.tsx
  src/components/MapViewer.tsx
  src/components/SearchResultButton.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/states/index.ts
  src/utils/index.ts
  src/utils/search.ts
  vite.config.ts
Labels: 개선

#42 gh-pages 라이브러리 설치
  package-lock.json
  package.json
Labels: 버그

#46 브랜치 최신화
  package-lock.json
  package.json
  src/components/SearchResultButton.tsx
Labels: 개선

#47 소스 코드 오류 수정 및 디버깅
  src/App.tsx
  src/components/BuildingDetailDrawer.tsx
  src/components/MapViewer.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
Labels: 버그

#48 소스 코드 오류 수정 및 디버깅
  src/App.tsx
  src/components/BuildingDetailDrawer.tsx
  src/components/MapViewer.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
Labels: 버그

#49 웹 애플리케이션 편의성 기능 구현
  src/components/BuildingDetailDrawer.tsx
  src/components/BuildingLayoutViewer.tsx
  src/components/BuildingMarker.tsx
  src/components/DrawerMenu.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HighlightedText.tsx
  src/components/MapViewer.tsx
  src/components/SearchDrawer.tsx
  src/components/SearchResultButton.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
Labels: 개선

#51 지도 뷰어 내 오류 수정
  src/components/CircularMarker.tsx
  src/components/MapViewer.tsx
Labels: 버그

#52 지도 뷰어 내 오류 수정
  src/components/CircularMarker.tsx
  src/components/MapViewer.tsx
Labels: 버그

#53 지도 뷰어 내 위치 따라가기 기능 수정
  src/components/MapViewer.tsx
Labels: 개선

#56 내 위치 따라가기 기능 로직 수정
  src/components/MapViewer.tsx
Labels: 개선

#57 오류 수정 및 누락된 데이터 추가
  src/assets/facilities.json
  src/components/MapViewer.tsx
Labels: 버그
