Repository Vactor0911/mokwon-guide, pull requests merged in 2025-04, with the labels that each got.

#1 시작 포트번호 3005번으로 수정
  package.json
Labels: 개선

#5 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
Labels: 문서화

#4 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
Labels: 문서화

#6 Vactor0911
  package.json
  src/components/FontTest.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/index.ts
  src/theme/index.ts
  vite.config.ts
Labels: 개선

#7 개발 환경 구성
  package.json
  src/components/FontTest.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/index.ts
  src/theme/index.ts
  vite.config.ts
Labels: 개선

#8 헤더 구현
  src/App.tsx
  src/components/Header.tsx
  src/pages/Main.tsx
  src/theme/index.ts
Labels: 개선

#9 헤더 및 푸터 구현
  index.html
  package-lock.json
  src/App.tsx
  src/assets/icons/GitHub.png
  src/assets/icons/Github.svg
  src/assets/icons/Mokwon.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/theme/index.ts
Labels: 개선

#10 헤더 및 푸터 구현
  index.html
  package-lock.json
  src/App.tsx
  src/assets/icons/GitHub.png
  src/assets/icons/Github.svg
  src/assets/icons/Mokwon.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/theme/index.ts
Labels: 개선

#11 헤더 및 드로어 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/App.tsx
  src/assets/buildings.json
  src/components/DrawerMenu.tsx
  src/components/DrawerNavLink.tsx
  src/components/Header.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/states/index.ts
Labels: 개선

#13 Link 목표 주소 오류 수정
  src/components/DrawerMenu.tsx
Labels: 버그

#12 헤더 및 드로어 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/App.tsx
  src/assets/buildings.json
  src/components/DrawerMenu.tsx
  src/components/DrawerNavLink.tsx
  src/components/Header.tsx
  src/pages/About.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/states/index.ts
Labels: 개선
